calibrated: 1
equilibrium:
    sign: -1
    signFlexor: 1
    signExtensor: -1
    nameFlexor: "wrist_flexor"
    nameExtensor: "wrist_extensor"
    servoRange: 5.4978
    servoOffset: 0.0
signEncoder: -1
signJoint: 1
name: "wrist_pitch"
nameEncoder: "wrist_encoder"
minAngle: -1.0
maxAngle: 0.65
maxAbsForwardError: 5.0
gains:
    P: 0.03
    I: 0.0
    D: 0.2
restingPoseAngle: 0.0

    # These PID values will be faster (instantly reach position but not overshoot)
    # P: 0.066    # effects deceleration, Higher number, causes later deceleration
    # I: 0.00001  # i should be very small (VERY SMALL!!!!), will cause hysterysis
    # D: 0.19     # Effects how much it fights force to reach destination, larger value more acceleration
